### PR TITLE
automatic provisioner and teardown features

### PR DESCRIPTION
**Pull request by IPvSean**
What does the provisioner take care of automatically?
- AWS VPC creation (Amazon WebServices Virtual Private Cloud)
- Creation of an SSH key pair (stored at ./ansible.pem)
  - This private key is installed automatically
- Creation of a AWS EC2 security group
- Creation of a subnet for the VPC
- Creation of an internet gateway for the VPC
- Creation of route table for VPC (for reachability from internet)

### CODE REVIEW

**Comment by petebowden** [comment]
One thought, what if I want to supply an existing VPC? I'd like to be able to specify one.

Also I think we should allow a prefix on all resources created in case we're deploying in a shared environment.

I'm all for merging this in and then enhancing as we go forward.

**Comment by IPvSean** [comment]
>
> One thought, what if I want to supply an existing VPC? I'd like to be able
> to specify one.
>
Should be trivial for me to add, merge this in and I will have a 2nd PR
today with a knob...

For VPC I did a suffic... (not sure why) I can change this to prefix->
  ec2_vpc_net:
    name: "vpc-{{ ec2_name_prefix }}"

For the SG I just re-used what was there, I could add a prefix there->
  ec2_group:
    name: insecure_all

For ec2_vpc_subnet, there isn't really a name, do you want me to tag it?

The key was just named the prefix.. I could change to prefix_key or
something?

For the route table I think you have to tag as well, not sure if there is a
name
ec2_vpc_route_table<-

I can merge that in... I will double check vpc_subnet and route_table to
see if I can name it, if I can't can I just tag it?

**Comment by petebowden** [comment]
So for the VPC, if I supply one in the vars file, in a specific format then the deployer should not create one, right?

Prefix or suffix is good :-). I misunderstood and thought that you mean it was hard coded to the ec2 region so it wasn't user selectable, so ignore that.

For the subnet... that's a good question. If I rerun the deployer, will we end up creating an additional subnet?

I think we should, wherever possible, tag or name things uniquely so that if we rerun the deployer we  don't create another copy. This in theory would allow you to supply whichever components you want to and then the provisioner use them and create the rest (including ec2, not sure why you would want to but it would allow for it)

**Comment by IPvSean** [comment]
Close this PR and I'll open a new one shortly with those fixes

Sean Cavanaugh
251-599-0209

**Comment by IPvSean** [comment]
@petebowden look at https://github.com/ansible/lightbulb/pull/228

**Pull request closed without merging**
