### PR TITLE
Create VPC Automatically

### PR DESCRIPTION
**Pull request by cigamit**
Create VPC, Subnet, Gateway, and Routes automatically
Teardown VPC, etc.. when destroying the lab environment
Change Security Group to only allow SSH, HTTP, and HTTPS
Change include to include_tasks to correct warning
Increase timeouts slightly until we can use wait_for_connection
Add new options and remove old ones from vars.yml example in Readme (we no longer need vpc_id or subnet_id).  New required variables are "ec2_vpc_cidr_block" and "ec2_availibility_zone".  Hopefully the AZ can be automated in the future.

### CODE REVIEW

**Comment by IPvSean** [comment]
@cigamit were you working off my pull request here->https://github.com/ansible/lightbulb/pull/237

I already have everything you are highlighting in this PR in review process

**Comment by cigamit** [comment]
I was at the Train the Trainer session, and an interest was expressed in having the VPC created automatically, so I created this.  They mentioned there may be others PRs out there, but the sheer amount of changes that they were making at once was unwieldy and should be broken up to be more easily tested.  I saw you had some VPC stuff in yours, but figured another attempt to get around that particular road block and get this particular piece in would be beneficial to all.  I can withdraw it if you want.

**Comment by IPvSean** [comment]
Who specifically saying what? Curious who said the PR was unwieldy.  Can
you encourage others to discuss this in this PR or mine or the lightbulb
mailing list? I can't really address or fix my PR if no one is telling me
what is going on.  Does this PR also update the teardown?

What train the trainer session was this?

Sean Cavanaugh
251-599-0209

**Comment by cigamit** [comment]
No one specifically mentioned your PR in this context.  Maybe I should rephrase.  In general, it was mentioned that when committing to the project, that it is better to create smaller, more concise PR requests than large unwieldy ones as they are easier to test and are then ofcourse faster to be get accepted.  1 PR per feature, instead of 1 PR with 30 different features that must all tested before any of it can be accepted.  You run less chance of the entire PR being held up because of 1 issue.  This is the same with every project I have ever worked on, so I don't see any issues with it.

Your PR seemed to have been held up because of the amount of testing that was required, so I created this one in an attempt to get a much needed feature in faster.  I will just close this, and we can wait on yours and I will go back to working on my own fork.

**Comment by IPvSean** [comment]
The reason I am asking is because there was multiple PRs and I was told to
combine them. I am just really confused where this direction is coming from
because it's wasting your time and mine where duplication of tasks is
happening.

Sean Cavanaugh
251-599-0209

**Pull request closed without merging**
