### PR TITLE
Adding an example for Google Cloud Platform

### PR DESCRIPTION
**Pull request by vincepower**

### CODE REVIEW

**Comment by vincepower** [comment]
closing, will refactor so it can be used as workshop if required

**Comment by thaumos** [comment]
can this be migrated to linklight? @IPvSean or @vincepower?

**Comment by kyleabenson** [comment]
What about a reinvigorated Ansible/examples?

**Comment by vincepower** [comment]
I can migrate it anywhere you want, for now I'm expanding it to three VMs and a load balancer at the moment, and keeping it in https://github.com/vincepower/gcp-ansible-sample

**Pull request closed without merging**
