### PR TITLE
Feature  #177: Extend Provisionner to support Network automation

### PR DESCRIPTION
**Pull request by victorock**
Add network provisionner under tools/network.

### CODE REVIEW

**Comment by tima** [comment]
Thank for the suggestion. It's definitely on our roadmap. It needs #141 to happen before we can support that.

**Comment by tima** [comment]
cc: @abenokraitis @jmcleroy

**Comment by IPvSean** [comment]
can we close this issue when https://github.com/ansible/lightbulb/pull/237 is closed, and then put more specific issues per networking use-case (e.g. cisco lab on GCE, cisco lab on aws, arista on aws, etc)

**Comment by tima** [comment]
@victorock Thanks for this submission. I really appreciate it. In light of all the work being done by @IPvSean I'm going to close this. I know you have some different and interesting ideas I'd like to explore, but let's circle back to that once we get something basic done first.

**Pull request closed without merging**
