### PR TITLE
ansible-lint is a code quality tool. Now all examples comply.

### PR DESCRIPTION
**Pull request by bbaassssiiee**
Use ansible-lint to discover elements in your ansible code that do not adhere to best practices.

**Installing**

```
pip install ansible-lint
```

**Usage**

```
ansible-lint top-level-playbook.yml
```

### CODE REVIEW

**Comment by gundalow** [comment]
Nice
Bonus points if you were to add running `ansible-lint` to Shippable/Travis

**Comment by gundalow** [comment]
Oh, don't seem to have any CI for this repo :(

**Comment by bbaassssiiee** [comment]
More bonus points?

**Comment by gundalow** [comment]
eeeeeeven more bonus points. I've mentioned it on Ansible Slack, though I don't see you there :(

My comments should block you doing this, can be added after. Will discuss with Tim A, etc

**Comment by bbaassssiiee** [comment]
What keeps us from merging?

**Comment by tima** [comment]
Looks fine that I merged it. I need to create a ticket for exploring ansible-lint use -- in particularly if it's default rules align with the best practices Ansible presents.

**Pull request merged**
