### PR TITLE
master

### PR DESCRIPTION
**Pull request by oatakan**
@tima updated the pull request removing commits for vagrant

### CODE REVIEW

**Comment by tima** [comment]
@sumerli Appreciate the work. Can you please split bbb60c7 out of this PR and resubmit? I'm OK with that commit to improve the speed of the AWS provisioner. The other vagrant related commits is not an option we want to pursue now especially for classroom labs that I'd like to hold on that for later review.

**Comment by sumerli** [comment]
@tima made the change you requested on the PR. thanks.

**Comment by samdoran** [comment]
@sumerli What's the purpose of the `until` loops added to several tasks?

**Comment by sumerli** [comment]
@samdoran I had some jobs failed during yum update potentially due to network connection issues. This was a transient issue though.

**Comment by defionscode** [comment]
Now there's just merge conflicts

**Comment by defionscode** [comment]
@oatakan for the intermittent network issues, I've seen this before on AWS and have been able to consistently not get 404's etc if I restart network services before trying to do any kind of internet-based network action (like yum). Have you tried doing this?

**Comment by oatakan** [comment]
@defionscode I will try that next time. Anything I can do to help move this PR move forward?

**Comment by defionscode** [comment]
@oatakan well right now the issue is merge conflicts if we can get those resolved then we can properly test

**Comment by tima** [comment]
The real holdup with merging PR (even if all of the conflicts were resolved) and PR #128 is that we need to do an extensive refactor of the lab provisioner "yesterday." In that context, enhancing what's there now seems like unnecessary effort.

**Comment by tima** [comment]
@oatakan I'm going to close this PR because it's gone way past it's original intent since it is linked to your master and all of your commits to it are being posted to this thread.

**Pull request closed without merging**
