### PR TITLE
[WIP] adding lab-guide for ansible-workshops

### PR DESCRIPTION
**Pull request by gdykeman**
Creating a new directory calling lab-guide that contains all the necessary files for the most recent lab-guide repository. 

Revised the lab-guide to be modular and allow for add-ons of additional ansible-workshops.

The current sample of how the lab guide looks is here:
http://ansible.redhatgov.io/

### CODE REVIEW

**Comment by tima** [comment]
Thanks for submitting this @gdykeman. I've marked this one WIP so we can work on fitting into lightbulb. May need to split the network examples from the workshop doc commits. We just got #177 and #178 that loosely relates to those examples -- how do we provide portable and repeatable hands-on ansible netops workshops? Open to suggestions and contributions.

**Comment by tima** [comment]
I don't mean to be a pain here @gdykeman, but would it be possible to split the two commits I see here into two separate PRs? It's a best practice to create a feature branch off of your targets master branch, make your changes and push that feature branch. Once merged you can kill the feature branch. 

https://www.atlassian.com/git/tutorials/comparing-workflows#feature-branch-workflow

The workshop guide and network examples are two very different topics and discussions. Keeping them separate keeps the context focused and let's each contribution move at its own nature pace.

Thanks.

**Comment by gdykeman** [comment]
I removed the network examples and have this PR only containing the workshop guide.  I'll submit another one from a separate branch for the network examples after we do some additional testing.

**Comment by tima** [comment]
@gdykeman Just to let you know I haven't forgotten about this PR. I've trying to figure out how to extract the document from ansible.redhatgov.io from what you committed to attempt converting it to a markup doc. There seems to be a lot of publishing tool configuration and what not in there. I'm not saying it can't be done -- just that it won't be quick and easy for me to do before merging. Like all things finding the time to do that is what is holding this PR up.

**Comment by bhirsch70** [comment]
@tima and @gdykeman I don't know if this would be easier or more difficult, but I had begun the process of converting this documentation using Hugo, examples of which can be seen at redhatgov.io and instructions can be found at http://redhatgov.io/workshops/example/ .  Maybe worth taking a look.  Still uses asciidoc but in a much simpler way in my opinion than the method we currently used to build this.

**Comment by tima** [comment]
@bhirsch70: Thanks for the input. This required too much back-and-forth that I did some DM'ing with @gdykeman to understand the intent of this content and how does this fit into lightbulb. Here is my summary of what (I think -- correct me if I get this wrong @gdykeman) I think we worked out:

* These guides introduce a third mode of Ansible workshop delivery -- "guided examples." We had lecture and hands-on workshops previously. Guided examples let an facilitator address larger audiences and are better suited for students who are less adept with a bash prompt. So it's the middle ground.
* These guides mostly line up with the breaks in the existing decks today. They opt for the apache content rather then introduce nginx as the workshops assignments do.
* This content introduces some features and syntax that facilitators presenting the lightbulb content found needed to be covered that is not in the existing decks. **That needs to get identified, extracted and contributed back throughout the rest of the lightbulb content.**

This all sounds reasonable to me though this PR is no where in the shape it needs to be to merge this in. Probably not worth fixing this PR, but submitting a handful of new ones. I'm going to leave it open for now though.

* The Ansible Essentials and Intro to Tower guides should be separate PRs and without all of the CMS cruft (javascript, config etc files) that are in here. Converting these docs to markup would be ideal. See https://tinyapps.org/blog/nix/201701240700_convert_asciidoc_to_markdown.html and https://stackoverflow.com/questions/7323596/is-there-any-way-to-convert-markdown-to-asciidoc-or-be-able-to-produce-the-same.
* The network automation guide should be coordinated with the workshop in progress. Again a seperate PR and really should have an issue filed. 
* We need to files a few issues to publish this content somewhere to make it easier to see and consume by all. I will take this item up.

**Comment by dfederlein** [comment]
This is an awesomely productive PR, even if it's not merged.  Let me know how I can help guys.

**Comment by bhirsch70** [comment]
So @tima and @gdykeman , is the consensus here to convert this to markdown?  If so, I'm happy to get started on that.

**Comment by gdykeman** [comment]
@tima @bhirsch70
So, I'm thinking a refactoring of this would be good. Depending on the language we agree on with @tima we (@bhrisch70 and I)  can block out a week to sync up and convert this. As of now, there certainly is a bunch of stuff that can be cleaned up in the directories utilized by asciidoc.

**Comment by tima** [comment]
@bhirsch70 and @gdykeman: Markdown would be great. Thanks. I know you used asciidoc which is the standard you used as it is the standard elsewhere. Markdown is what Ansible was using and in getting things out quickly kept to. I also think it's more common in the broader github/open source community. There are tools (pandoc?) for converting from asciidoc to Markdown via Docbook if that helps here.

@gdykeman: One side note -- since this PR is based off of your master every commit you make is showing up as part of this. Not sure you actually intended on that.

**Comment by tima** [comment]
Closing this in favor of #250 and other follow-up efforts.

**Pull request closed without merging**
