### PR TITLE
Installation fix

### PR DESCRIPTION
**Pull request by gdykeman**
Control_node/tasks/main.yml
Changed enablerepo to be Rhel-7-extras for successful ansible installation
```
- name: Install Ansible
  yum:
    name:
      - sshpass
      - ansible
    state: latest
    enablerepo: rhui-REGION-rhel-server-extras
  tags:
    - control_node
    - control
  when: control_node_install_ansible
```

control_node/defaults/main.yml
Edited the control_node_inventory_path to point to the absolute path of the inventory file.  Current bug in 2.4 when referencing a directory.
```
control_node_inventory_path: ~{{ username }}/lightbulb/lessons/lab_inventory/{{ username }}-instances.txt
```

### CODE REVIEW

**Comment by wenottingham** [comment]
... this appears to be against the wrong branch? At least, it contains way more than fixing ansible installation.

**Comment by tima** [comment]
Yeah wow. There are 547 files in the PR. Seems excessive. ;)

**Comment by gdykeman** [comment]
My mistake. Let me fix that and resubmit

**Comment by tima** [comment]
I'm going to close this. I think I cherry-picked the one commit that was supposed to make up this PR and merged it thru #208.

**Pull request closed without merging**
