### PR TITLE
split out firewall services and ports for firewalld syntax

### PR DESCRIPTION
**Pull request by GoKEV**

### CODE REVIEW

**Comment by samdoran** [comment]
This could be combined into a [single task](https://github.com/samdoran/ansible-role-firewall/blob/master/tasks/configure-firewalld.yml#L55) by changing the input to a dictionary.

```yaml
firewall_rules:
  - port: 22
    protocol: tcp
  - service: dhcp
```

**Comment by GoKEV** [comment]
The latest commit added ports in the same list as service names.  As far as I can tell, the firewalld module can only handle valid services when invoked with 'service'.  When invoked with 'port', valid options are number/proto.

I don't see a way to reduce this into one single list of ports and services, but I may be missing something.

**Comment by samdoran** [comment]
I linked to an example task.


```yaml
- name: FIREWALLD | Configure additional firewalld rules
  firewalld:
    immediate: "{{ item.immediate | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    masquerade: "{{ item.masquerade | default(omit) }}"
    permanent: "{{ item.permanent | default('yes') }}"
    port: "{{ item.port ~ '/' ~ item.protocol if (item.port is defined and item.protocol is defined) else omit }}"
    rich_rule: "{{ item.rich_rule | default(omit) }}"
    service: "{{ item.service | default(omit) }}"
    source: "{{ item.source | default(omit) }}"
    state: "{{ item.state | default('enabled') }}"
    timeout: "{{ item.timeout | default(omit) }}"
    zone: "{{ item.zone | default(omit) }}"
  with_items: "{{ firewall_rules }}"
```

**Comment by tima** [comment]
@GoKEV did you mean to close this without merging?

**Comment by tima** [comment]
Sorry @GoKEV. I just saw you and @samdoran committed something similar thru another PR or the like.

**Pull request closed without merging**
